name: on-pull-request
on: [pull_request]

jobs:
  ktlint:
    name: Check Code Quality
    runs-on: ubuntu-latest

    steps:
      - name: Clone repo
        uses: actions/checkout@v3
      - name: ktlint
        run: ./gradlew ktlintCheck