name: code-style-check

on: [pull_request]

jobs:
  ktlint:
    name: Code Style Check
    runs-on: ubuntu-latest
    steps:
      - name: Clone repo
        uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'zulu'

      - name: ktlint
        run: ./gradlew ktlintCheck